"""Friendship graph helpers shared by every social endpoint.

Gameplay ledgers stay device-keyed (`01_CORE_MECHANICS`), while friends,
challenges and races are account-level. `account_device_ids` is the seam between
the two: anything that measures a player's movement resolves an account to all of
its devices first, so a challenge counts a run recorded on any linked device.
"""

import re
import uuid
from datetime import UTC, datetime, timedelta

from fastapi import HTTPException
from sqlalchemy import or_, select
from sqlalchemy.orm import Session

from app.models import (
    Account,
    DeviceLink,
    FriendShareSettings,
    Friendship,
    LivePosition,
    SocialEvent,
)

HANDLE_PATTERN = re.compile(r"^[a-z0-9_]{3,24}$")

# Reserved so a player cannot impersonate the platform or an operations account.
RESERVED_HANDLES = frozenset(
    {"admin", "administrator", "terrarun", "support", "help", "system", "moderator", "staff"}
)


def normalise_handle(value: str) -> str:
    """Validate a player-chosen handle. Storage is always lowercase."""
    handle = value.strip().lstrip("@").lower()
    if not HANDLE_PATTERN.match(handle):
        raise HTTPException(
            422, "Handles are 3–24 characters, using letters, numbers or underscores."
        )
    if handle in RESERVED_HANDLES:
        raise HTTPException(422, "That handle is reserved.")
    return handle


def handle_for(session: Session, account: Account) -> str:
    """Read an account's handle, fetching the trigger-assigned value if needed.

    The handle is generated by a database trigger, so an account object created
    in this transaction has no value loaded until it is flushed and refreshed.
    """
    if account.handle is None:
        session.flush()
        session.refresh(account, ["handle"])
    return account.handle


def account_device_ids(session: Session, account_id: uuid.UUID) -> list[uuid.UUID]:
    """Every device linked to an account, for aggregating that player's runs."""
    return list(
        session.execute(
            select(DeviceLink.device_id).where(DeviceLink.account_id == account_id)
        ).scalars()
    )


def friendship_between(
    session: Session, left: uuid.UUID, right: uuid.UUID
) -> Friendship | None:
    """The single row for this pair, whichever side opened it."""
    return session.execute(
        select(Friendship).where(
            or_(
                (Friendship.requester_id == left) & (Friendship.addressee_id == right),
                (Friendship.requester_id == right) & (Friendship.addressee_id == left),
            )
        )
    ).scalar_one_or_none()


def friend_ids(session: Session, account_id: uuid.UUID) -> set[uuid.UUID]:
    """Accounts with an accepted friendship, in either direction."""
    rows = session.execute(
        select(Friendship.requester_id, Friendship.addressee_id).where(
            Friendship.status == "accepted",
            or_(Friendship.requester_id == account_id, Friendship.addressee_id == account_id),
        )
    ).all()
    return {requester if addressee == account_id else addressee for requester, addressee in rows}


def require_friend(session: Session, account_id: uuid.UUID, other_id: uuid.UUID) -> Friendship:
    """Gate a feature on an accepted friendship.

    The error is deliberately identical for "not friends" and "blocked you", so
    the endpoint cannot be used to detect a block.
    """
    friendship = friendship_between(session, account_id, other_id)
    if friendship is None or friendship.status != "accepted":
        raise HTTPException(403, "You can only do this with an accepted friend.")
    return friendship


def blocked_account_ids(session: Session, account_id: uuid.UUID) -> set[uuid.UUID]:
    """Both directions: people this account blocked, and people who blocked it."""
    rows = session.execute(
        select(Friendship.requester_id, Friendship.addressee_id).where(
            Friendship.status == "blocked",
            or_(Friendship.requester_id == account_id, Friendship.addressee_id == account_id),
        )
    ).all()
    return {requester if addressee == account_id else addressee for requester, addressee in rows}


def relationship_label(friendship: Friendship | None, viewer_id: uuid.UUID) -> str:
    """How a searching player should see another account's row."""
    if friendship is None:
        return "none"
    if friendship.status == "accepted":
        return "friends"
    if friendship.status == "blocked":
        return "blocked" if friendship.blocked_by == viewer_id else "none"
    if friendship.status == "pending":
        return "request_sent" if friendship.requester_id == viewer_id else "request_received"
    return "none"


def search_accounts(session: Session, viewer_id: uuid.UUID, query: str, limit: int = 20):
    """Find accounts by exact id, exact/prefix handle, or display-name prefix.

    Prefix-only matching is deliberate: substring search over display names turns
    the account list into a directory to browse, which is the shape of a stalking
    tool rather than a way to add someone you already know.
    """
    text = query.strip().lstrip("@")
    if len(text) < 2:
        raise HTTPException(422, "Enter at least 2 characters to search.")

    statement = select(Account).where(Account.id != viewer_id)
    try:
        statement = statement.where(Account.id == uuid.UUID(text))
    except ValueError:
        pattern = f"{text.lower()}%"
        statement = statement.where(
            or_(Account.handle.like(pattern), Account.display_name.ilike(pattern))
        )

    hidden = blocked_account_ids(session, viewer_id)
    found = session.execute(statement.order_by(Account.handle).limit(limit + len(hidden))).scalars()
    return [account for account in found if account.id not in hidden][:limit]


# --- Presence ---------------------------------------------------------------

# A position older than this is not shown at all. Sharing therefore stops being
# visible as soon as a player stops reporting, without them having to remember
# to switch it off.
POSITION_FRESHNESS = timedelta(seconds=120)


def sharing_setting(
    session: Session, owner_id: uuid.UUID, viewer_id: uuid.UUID, *, create: bool = False
) -> FriendShareSettings | None:
    setting = session.get(FriendShareSettings, (owner_id, viewer_id))
    if setting is None and create:
        setting = FriendShareSettings(owner_id=owner_id, viewer_id=viewer_id)
        session.add(setting)
        session.flush()
    return setting


def location_is_shared(setting: FriendShareSettings | None, now: datetime | None = None) -> bool:
    """True while `viewer` may see `owner`, honouring a temporary grant's expiry."""
    if setting is None or not setting.share_location:
        return False
    if setting.location_expires_at is None:
        return True
    return setting.location_expires_at > (now or datetime.now(UTC))


def grant_temporary_location(
    session: Session, owner_id: uuid.UUID, viewer_id: uuid.UUID, until: datetime
) -> None:
    """Share location for a bounded window without disturbing a standing choice.

    A player who already shares permanently keeps that setting untouched, so
    ending the race cannot silently switch off something they had turned on.
    """
    setting = sharing_setting(session, owner_id, viewer_id, create=True)
    if setting.share_location and setting.location_expires_at is None:
        return
    setting.share_location = True
    setting.location_expires_at = max(until, setting.location_expires_at or until)


def revoke_temporary_location(
    session: Session, owner_id: uuid.UUID, viewer_id: uuid.UUID
) -> None:
    """End a temporary grant early; leaves a permanent grant alone."""
    setting = sharing_setting(session, owner_id, viewer_id)
    if setting is not None and setting.location_expires_at is not None:
        setting.share_location = False
        setting.location_expires_at = None


def viewers_of(session: Session, owner_id: uuid.UUID) -> list[uuid.UUID]:
    """Friends currently allowed to see this account's live position."""
    now = datetime.now(UTC)
    settings = session.execute(
        select(FriendShareSettings).where(
            FriendShareSettings.owner_id == owner_id,
            FriendShareSettings.share_location.is_(True),
        )
    ).scalars()
    allowed = friend_ids(session, owner_id)
    return [
        setting.viewer_id
        for setting in settings
        if setting.viewer_id in allowed and location_is_shared(setting, now)
    ]


def visible_positions(session: Session, viewer_id: uuid.UUID) -> list[tuple[Account, LivePosition]]:
    """Fresh positions of friends who are sharing with this viewer."""
    now = datetime.now(UTC)
    rows = session.execute(
        select(Account, LivePosition, FriendShareSettings)
        .join(FriendShareSettings, FriendShareSettings.owner_id == Account.id)
        .join(LivePosition, LivePosition.account_id == Account.id)
        .where(
            FriendShareSettings.viewer_id == viewer_id,
            FriendShareSettings.share_location.is_(True),
            LivePosition.updated_at > now - POSITION_FRESHNESS,
        )
    ).all()
    allowed = friend_ids(session, viewer_id)
    return [
        (account, position)
        for account, position, setting in rows
        if account.id in allowed and location_is_shared(setting, now)
    ]


def record_event(
    session: Session,
    account_id: uuid.UUID,
    kind: str,
    body: str,
    *,
    actor_id: uuid.UUID | None = None,
    subject_id: uuid.UUID | None = None,
) -> SocialEvent:
    """Queue one in-app notification. Delivery is by polling; nothing is pushed."""
    event = SocialEvent(
        account_id=account_id,
        kind=kind,
        body=body[:240],
        actor_id=actor_id,
        subject_id=subject_id,
    )
    session.add(event)
    return event
