import Constants from 'expo-constants';
import { router, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { getNotificationsEnabled, getUnits, setNotificationsEnabled, setUnits, type UnitPreference } from '@/lib/preferences';
import { colors, fontSize, fontWeight, radius, spacing } from '@/theme';

export default function SettingsScreen() { const [units,setUnitsState]=useState<UnitPreference>('km'); const [notifications,setNotifications]=useState(true); useFocusEffect(useCallback(()=>{void Promise.all([getUnits(),getNotificationsEnabled()]).then(([u,n])=>{setUnitsState(u);setNotifications(n);});},[])); const choose=(u:UnitPreference)=>{setUnitsState(u);void setUnits(u);}; return <SafeAreaView style={styles.screen} edges={['top']}><View style={styles.header}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Profile</Text></Pressable><Text style={styles.title}>Settings</Text><View /></View><Text style={styles.label}>UNITS</Text><View style={styles.segment}>{(['km','mi'] as const).map(u=><Pressable key={u} onPress={()=>choose(u)} style={[styles.option,units===u&&styles.selected]}><Text style={[styles.optionText,units===u&&styles.selectedText]}>{u === 'km' ? 'Kilometres' : 'Miles'}</Text></Pressable>)}</View><View style={styles.row}><View><Text style={styles.rowText}>Notifications</Text><Text style={styles.subtext}>Run and territory updates</Text></View><Switch value={notifications} onValueChange={v=>{setNotifications(v);void setNotificationsEnabled(v);}} /></View><Text style={styles.footer}>run {Constants.expoConfig?.version ?? '1.0.0'}{`\n`}© OpenStreetMap contributors</Text></SafeAreaView>; }
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background,padding:spacing.lg},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:spacing.xl},back:{color:colors.primary,fontWeight:fontWeight.semibold},title:{fontSize:fontSize.lg,fontWeight:fontWeight.bold,color:colors.text},label:{fontSize:11,fontWeight:fontWeight.bold,color:colors.textMuted,letterSpacing:1,marginBottom:spacing.sm},segment:{flexDirection:'row',borderWidth:1,borderColor:colors.border,borderRadius:radius.md,overflow:'hidden'},option:{flex:1,padding:spacing.md,alignItems:'center'},selected:{backgroundColor:colors.primary},optionText:{color:colors.text},selectedText:{color:colors.surface,fontWeight:fontWeight.bold},row:{marginTop:spacing.xl,paddingVertical:spacing.md,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderTopWidth:1,borderBottomWidth:1,borderColor:colors.border},rowText:{fontSize:fontSize.md,fontWeight:fontWeight.semibold,color:colors.text},subtext:{fontSize:fontSize.xs,color:colors.textMuted,marginTop:3},footer:{marginTop:'auto',textAlign:'center',color:colors.textMuted,fontSize:fontSize.xs,lineHeight:18}});
